services:
  server:
    build:
      context: .
      args:
        # Future considerations: pass the connections string in as secret or as an env, instead of args
        - POSTGRES_CONNECTION=postgresql://postgres:password123@db/example
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: dock-to-do-db
    build:
      context: ./docker/db
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-password:
    file: db/password.txt
