name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create postgres pwd file
        run: |
          mkdir /home/runner/work/dock-to-do/dock-to-do/db
          echo "${{ secrets.LOCAL_PG_PWD }}" > /home/runner/work/dock-to-do/dock-to-do/db/password.txt
      - name: Start Container
        run: docker compose up -d --build

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            POSTGRES_CONNECTION=${{ secrets.POSTGRES_CONNECTION }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME  }}/dock-to-do-server:amd
